In [1]:
# QUESTION 1

s = "yash agarwal"
print(s[::-1])

lawraga hsay


In [2]:
#QUESTION 2

s = 'madam'
if s==s[::-1]:
    print("Yes, String is palindrome")
else:
    print("No, String is not palidrome")

Yes, String is palindrome


In [3]:
# Question 3

import numpy as np
l = np.random.randint(100, size=10)
max = l[0]
for i in l:
    if i>max:
        max=i
print(f"From the list {l}, the largest number is {max}")

From the list [43 60 68 91 74  3 51 93 99 57], the largest number is 99


In [4]:
# QUESTION 4

def occ(s):
    d={}
    s = [x for x in s]
    for i in s:
        if i in d:
            v = d[i]
            d[i] = v+1
        else:
            d[i]=1
    return d
s = "The quick brown fox jumps over the lazy dog"
s = 'yash agarwal'
d = occ(s)
print(d)

{'y': 1, 'a': 4, 's': 1, 'h': 1, ' ': 1, 'g': 1, 'r': 1, 'w': 1, 'l': 1}


In [5]:
# QUESTION 5
import numpy as np

l = np.random.randint(100, size = 10)
s = set(l)
s = list(s)
s.sort()
print("For list {} the second largest number is {}".format(l, s[-2]))

For list [21 55  1 13 14 23 19 71 46 23] the second largest number is 55


In [6]:
# Question 6

def removeDup(l):
    return list(set(l))
l = np.random.randint(90, 100, size = 10)
m = removeDup(l)

print("For list {} the list with no duplicate element is {}".format(l,m))

For list [90 90 91 90 99 96 99 98 95 93] the list with no duplicate element is [96, 98, 99, 90, 91, 93, 95]


In [7]:
# Question 7

n = 5
f = 1
for i in range(1, n+1):
    f = f*i
print("Factorial of {} is {}".format(n, f))

Factorial of 5 is 120


In [8]:
# Question 8

def primeCheck(n):
    i=2
    r=n**0.5
    while(i<r):
        if(n%i==0):
            return False
        i=i+1
    return True
n = np.random.randint(100)
b = primeCheck(n)
if b:
    print("{} is a prime".format(n))
else:
    print("{} is Not a Prime ".format(n))

99 is Not a Prime 


In [9]:
# Questin 9

l = np.random.randint(100, size = 10)
m = l.copy()
m.sort()

print("The sorted version of {} is {}".format(l,m))

The sorted version of [93 21  4  3 13 48 89 97 86 86] is [ 3  4 13 21 48 86 86 89 93 97]


In [10]:
#Question 10

l = np.random.randint(100, size = 10)
sum = 0

for i in l:
    sum = sum+i 
print("The sum of {} is {}".format(l,sum))

The sum of [ 3 87 25 69 15 45 86 77 94 65] is 566


In [11]:
#Question 11

l = np.random.randint(90, 100, size = 10)
m = np.random.randint(90, 100, size = 10)

print("Common elements of {} and {} are {}".format(l,m,set(l).intersection(set(m))))

Common elements of [93 99 90 91 97 91 92 91 95 95] and [92 96 99 93 95 92 96 98 95 93] are {99, 92, 93, 95}


In [12]:
#Question 12

l = 'abac'
m = 'cbaa'

x = []
y = []

for i in l:
    x.append(i)
for i in m:
    y.append(i)
    
x.sort()
y.sort()

if x==y:
    print("{} and {} are Anagrams".format(l,m))
else:
    print("{} and {} are not Anagrams".format(l,m))

abac and cbaa are Anagrams


In [13]:
# Question 13

s = 'abc'

print("All the subsets of {} is as follows ".format(s))
for i in range(len(s)):
    for j in range(len(s)):
        if j<i:
            continue
        print(s[i:j+1],end="  ")

All the subsets of abc is as follows 
a  ab  abc  b  bc  c  

In [14]:
# Question 14

def fibo(n):
    a=0
    b=1
    c=0
    count = 1
    while(count<=n):
        print(c, end=" ")

        a = b
        b = c
        c = a+b
        count=count+1
        
n = int(input("Enter a number"))
fibo(n)


Enter a number 10


0 1 1 2 3 5 8 13 21 34 

In [15]:
# Question 15
import numpy as np

n = np.random.randint(100, size = np.random.randint(10,15,size=1))
m = n.copy()
m.sort()
if(len(n)%2!=0):
    c = m[len(n)//2]
else:
    c = m[len(n)//2]+m[len(n)//2 - 1]
    c = c/2 
    
print("Median of {} is {}".format(n,c))    
print(m)

Median of [49 15 97 10  4 42 14 20 10 90 60 24] is 22.0
[ 4 10 10 14 15 20 24 42 49 60 90 97]


In [16]:
# Question 16

n = np.random.randint(100,size=10)

n = list(n)
m = n.copy()
m.sort()

if n==m:
    print("{} is in non-descending order".format(n))
else:
    print("{} is not in non-descending order".format(n))

[60, 27, 96, 7, 61, 50, 38, 63, 53, 15] is not in non-descending order


In [17]:
#Question 17

n = np.random.randint(90, 100, size = 10)
m = np.random.randint(90, 100, size = 10)

x = set(n.copy())
y = set(m.copy())

print("Common elements in {} and {} are {}".format(n, m, x.intersection(y)))

Common elements in [99 90 92 99 97 95 95 95 97 90] and [91 99 97 91 93 99 90 92 90 98] are {97, 90, 99, 92}


In [1]:
# Question 18
import numpy as np
def maxSum(nums):
    max_sum = nums[0]
    current_sum = nums[0]

    for num in nums[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)

    return max_sum

l = np.random.randint(100, size=10)
l = list(l)
print("Maximum sum of subarray is {}".format(maxSum(l)))

Maximum sum of subarray is 302


In [2]:
# Question 19

a = 'yash agarwal'
b = ""
vowels = ['a','e','i','o','u','A','E','I','O','U']
for i in a:
    if i in vowels:
        continue
    b = b+i
print("Modified string is {}".format(b))
    

Modified string is ysh grwl


In [3]:
# Question 20

def revWords(s):
    s = s.split()
    return s[::-1]
s = 'The quick brown fox jumps over the lazy dog'
t = revWords(s)
u = ""
for i in t:
    u=u+i+" "
print("reversal of words of string \n{} is \n{}".format(s,u))

reversal of words of string 
The quick brown fox jumps over the lazy dog is 
dog lazy the over jumps fox brown quick The 


In [4]:
#Question 21

l = 'abac'
m = 'cbaa'

x = []
y = []

for i in l:
    x.append(i)
for i in m:
    y.append(i)
    
x.sort()
y.sort()

if x==y:
    print("{} and {} are Anagrams".format(l,m))
else:
    print("{} and {} are not Anagrams".format(l,m))

abac and cbaa are Anagrams


In [5]:
# Question 22

def nonRepeat(s):
    s = list(s)
    for i in s:
        if s.count(i)==1:
            return i
    
s = 'yash yagarwal'
print("The first non-repeating from string {} is {}".format(s,nonRepeat(s)))

The first non-repeating from string yash yagarwal is s


In [6]:
# Question 23
import numpy as np
import math
def primeFactors(n):
     
    while n % 2 == 0:
        print (2),
        n = n / 2
         
    for i in range(3,int(math.sqrt(n))+1,2):
        while n % i== 0:
            print (i),
            n = n / i
             
    if n > 2:
        print(n)
primeFactors(100)

2
2
5
5


In [7]:
#Question 24

def powerTwo(n):
    if n <= 0:
        return False
    while n > 1:
        if n % 2 != 0:
            return False
        n = n // 2
    return True

n = 32
b = powerTwo(n)

if b==True:
    print("{} is in power of 2".format(n))
else:
    print("{} is not in power of 2".format(n))

32 is in power of 2


In [8]:
# question 25

m = np.random.randint(100, size=10)
m.sort()
n = np.random.randint(100, size=10)
n.sort()

c = []
c.extend(m)
c.extend(n)
c.sort()
print("Merged list of \n{} and\n{} is \n{}".format(m,n,c))

Merged list of 
[ 0  2 31 38 59 69 76 82 89 90] and
[10 15 36 37 38 43 44 56 76 84] is 
[0, 2, 10, 15, 31, 36, 37, 38, 38, 43, 44, 56, 59, 69, 76, 76, 82, 84, 89, 90]


In [9]:
# question 26
import numpy as np
n= [2, 2, 14, 27, 28, 32, 34, 36, 38, 39, 41, 44, 45, 46, 50, 53, 53, 58, 71, 97]
n = list(n)

d={}
for i in n:
    if i in d:
        d[i]=d[i]+1
    else:
        d[i]=1
        
mod = max(zip(d.values(), d.keys()))[1]
print("Mode of {} is {}".format(n,mod))

Mode of [2, 2, 14, 27, 28, 32, 34, 36, 38, 39, 41, 44, 45, 46, 50, 53, 53, 58, 71, 97] is 53


In [10]:
# question 27

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

num1 = np.random.randint(100)
num2 = np.random.randint(100)
result = gcd(num1, num2)
print("GCD of {} and {} is {}".format(num1, num2, result))

GCD of 3 and 18 is 3


In [11]:
# question 28

def sqr_root(n):
    return n**0.5

n = np.random.randint(100)
print("Sqaure root of {} is {}".format(n,sqr_root(n)))

Sqaure root of 78 is 8.831760866327848


In [12]:
# question 29

s = "m1a2d3a4m@5m4a%3d#2a1m@%"
c = ""
for i in s:
    if i.isalnum():
        c=c+i 
if c==c[::-1]:
    print("{} is a palindrome ignoring the non-alpha numeric terms".format(s))
else:
    print("{} is not a palindrome ignoring the non-alpha numeric terms".format(s))

m1a2d3a4m@5m4a%3d#2a1m@% is a palindrome ignoring the non-alpha numeric terms


In [13]:
# question 30

def findMin(l):
    left = 0
    right = len(l)-1
    
    while(left<right):
        mid = (left+right)//2
        if(l[mid]>l[right]):
            left = mid+1
        else:
            right = mid
    return l[left]
    
l = [4, 5, 6, 7,1,2,3]
min = findMin(l)
print("The minimum element in {} is {}".format(l,min))

The minimum element in [4, 5, 6, 7, 1, 2, 3] is 1


In [14]:
# question 31

def findSum(l):
    sum = 0
    for i in l:
        if i%2==0:
            sum=sum+i
            
    return sum
l = np.random.randint(100, size=10)
sum = findSum(l)

print("The sum of even elements of {} is {}".format(l,sum))

The sum of even elements of [97 58 15 97 68 91 80 16 35 96] is 318


In [15]:
# question 32

def po(n,p):
    if p>0:
        return (po(n,p-1)*n)
    else:
        return 1
    
n = np.random.randint(1,10)
n=int(n)
p = np.random.randint(1,10)
p = int(p)
result = po(n,p)
print("{}^{} is {}".format(n,p,result))

9^7 is 4782969


In [16]:
# question 33
import numpy as np
l = np.random.randint(10, 20, size=10)
m = l.copy()
l = list(l)
for i in l:
    if l.count(i)>1:
        l.remove(i)
print("Removing duplicates from {} gives {}".format(m,l))

Removing duplicates from [10 10 12 18 18 16 19 11 10 19] gives [12, 18, 16, 11, 10, 19]


In [1]:
# question 34
import math
def preCommon(m, n):
    res = ""
    l = min(len(m), len(n))

    for i in range(l):
        if m[i] != n[i]:
            break
        res += m[i]

    return res

# Example usage
m = "flower"
n = "flow"
res = preCommon(m, n)
print("The longest common prefix in {} and {} is {}".format(m,n,res))


The longest common prefix in flower and flow is flow


In [2]:
# question 35
import numpy as np
import math

n = np.random.randint(100)
m = n**0.5
if math.ceil(m)==m and math.floor(m)==m:
    print("{} is a perfect sqaure".format(n))
else:
    print("{} is not a perfect sqaure".format(n))

67 is not a perfect sqaure


In [3]:
#question 36

def prod(n):
    m = 1
    for i in n:
        m=m*i
    return m

n = np.random.randint(10, size = 10)
n = list(n)

print("Product of elements of {} is {}".format(n,prod(n)))

Product of elements of [3, 7, 0, 4, 0, 2, 9, 1, 5, 8] is 0


In [4]:
# Question 37 

def revWords(s):
    s = s.split()
    return s[::-1]
s = 'The quick brown fox jumps over the lazy dog'
t = revWords(s)
u = ""
for i in t:
    u=u+i+" "
print("Reversing the order of words while preserving the word order of \n{} is \n{}".format(s,u))

Reversing the order of words while preserving the word order of 
The quick brown fox jumps over the lazy dog is 
dog lazy the over jumps fox brown quick The 


In [5]:
# question 38

def missingVal(n):
    l = len(n)+1
    total = (l*(l+1))//2
    curr_sum = sum(n)
    return total-curr_sum

l = [1,2,3,4,5,6,8,9,10]
missValue = missingVal(l)
print("The missing value in {} is {}".format(l,missValue))

The missing value in [1, 2, 3, 4, 5, 6, 8, 9, 10] is 7


In [6]:
# question 39

l = np.random.randint(1000,9999)
l = int(l)
x = l
s = 0
while(x>0):
    r=x%10
    s=s+r
    x=x//10 
print("Sum of digits of {} is {} ".format(l,s))

Sum of digits of 5757 is 24 


In [7]:
# question 40

s = 'Madam'
if s==s[::-1]:
    print("{} is a palindrome string ".format(s))
else:
    print("{} is not a palindrome string".format(s))

Madam is not a palindrome string


In [8]:
# question 41

def missingVal(n):
    l = len(n)+1
    total = (l*(l+1))//2
    curr_sum = sum(n)
    return total-curr_sum

l = [1,2,3,4,5,6,8,9,10]
missValue = missingVal(l)
print("The smallest positive value in {} is {}".format(l,missValue))

The smallest positive value in [1, 2, 3, 4, 5, 6, 8, 9, 10] is 7


In [9]:
#question 42

def longestPal(s):
    n = len(s)
    if n < 2:
        return s

    max_l = 1
    st = 0

    for i in range(n):
        for j in range(i+1, n+1):
            stt = s[i:j]
            if stt == stt[::-1] and len(stt) > max_l:
                max_l = len(stt)
                st = i

    return s[st:st + max_l]


s = 'ababadcabababa'
print("Longest Palindrome in {} is {}".format(s,longestPal(s)))

Longest Palindrome in ababadcabababa is abababa


In [10]:
# question 43

n = np.random.randint(10, 20, size =10)
n = list(n)
val = np.random.randint(10)
val = n[val]
count = n.count(val)
print("Occurrence of {} in {} is {}".format(val, n, count))

Occurrence of 18 in [14, 10, 13, 17, 16, 12, 18, 11, 14, 17] is 1


In [11]:
# 44

def isPerfect(n):
    divisors = []
    for i in range(1,n):
        if n%i==0:
            divisors.append(i)
            
    if sum(divisors)==n:
        return True
    return False

n = 28
b = isPerfect(n)
if b:
    print(f"{n} is a perfect number")
else:
    print(f"{n} is not a perfect number")

28 is a perfect number


In [12]:
# question 45

s = 'yash agarwal'

u = ""
for i in s:
    if i not in u:
        u = u+i 
print("Removing duplicates from {} make string as {}".format(s,u))

Removing duplicates from yash agarwal make string as yash grwl


In [13]:
# question 46

def missingVal(n):
    l = len(n)+1
    total = (l*(l+1))//2
    curr_sum = sum(n)
    return total-curr_sum

l = [1,2,3,4,5,6,8,9,10]
missValue = missingVal(l)
print("The smallest missing positive value in {} is {}".format(l,missValue))

The smallest missing positive value in [1, 2, 3, 4, 5, 6, 8, 9, 10] is 7
